/*
 * Copyright (C) 2022-2025 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

[
    Conditional=WK_WEB_EXTENSIONS,
    ReturnsPromiseWhenCallbackIsOmitted,
    UseCPPAPI
] interface WebExtensionAPINamespace {

    [MainWorldOnly, Dynamic, CocoaOnly] readonly attribute WebExtensionAPIAction action;

    [MainWorldOnly, Dynamic] readonly attribute WebExtensionAPIAlarms alarms;

    [MainWorldOnly, Dynamic, CocoaOnly, Conditional=WK_WEB_EXTENSIONS_BOOKMARKS] readonly attribute WebExtensionAPIBookmarks bookmarks;

    [MainWorldOnly, Dynamic, CocoaOnly] readonly attribute WebExtensionAPIAction browserAction;

    [MainWorldOnly, Dynamic, CocoaOnly] readonly attribute WebExtensionAPICookies cookies;

    [MainWorldOnly, Dynamic, CocoaOnly] readonly attribute WebExtensionAPICommands commands;

    [MainWorldOnly, Dynamic, CocoaOnly] readonly attribute WebExtensionAPIMenus contextMenus;

    [MainWorldOnly, Dynamic, CocoaOnly] readonly attribute WebExtensionAPIDeclarativeNetRequest declarativeNetRequest;

    [Dynamic, CocoaOnly, Conditional=INSPECTOR_EXTENSIONS] readonly attribute WebExtensionAPIDevTools devtools;

    [CocoaOnly] readonly attribute WebExtensionAPIDOM dom;

    [CocoaOnly] readonly attribute WebExtensionAPIExtension extension;

    [CocoaOnly] readonly attribute WebExtensionAPILocalization i18n;

    [CocoaOnly] readonly attribute WebExtensionAPIRuntime runtime;

    [MainWorldOnly, Dynamic, CocoaOnly] readonly attribute WebExtensionAPIMenus menus;

    [MainWorldOnly, Dynamic, CocoaOnly] readonly attribute WebExtensionAPINotifications notifications;

    [MainWorldOnly, Dynamic, CocoaOnly] readonly attribute WebExtensionAPIAction pageAction;

    [MainWorldOnly, CocoaOnly] readonly attribute WebExtensionAPIPermissions permissions;

    [MainWorldOnly, Dynamic, CocoaOnly] readonly attribute WebExtensionAPIScripting scripting;

    [MainWorldOnly, Dynamic, CocoaOnly, Conditional=WK_WEB_EXTENSIONS_SIDEBAR] readonly attribute WebExtensionAPISidebarAction sidebarAction;

    [MainWorldOnly, Dynamic, CocoaOnly, Conditional=WK_WEB_EXTENSIONS_SIDEBAR] readonly attribute WebExtensionAPISidePanel sidePanel;

    [Dynamic, CocoaOnly] readonly attribute WebExtensionAPIStorage storage;

    [MainWorldOnly, CocoaOnly] readonly attribute WebExtensionAPITabs tabs;

    [MainWorldOnly, CocoaOnly] readonly attribute WebExtensionAPIWindows windows;

    [MainWorldOnly, Dynamic, CocoaOnly] readonly attribute WebExtensionAPIWebNavigation webNavigation;

    [MainWorldOnly, Dynamic, CocoaOnly] readonly attribute WebExtensionAPIWebRequest webRequest;

    [Dynamic] readonly attribute WebExtensionAPITest test;

};
